# Desafio Webscraping

In [1]:
import pandas as pd
import numpy as np

In [11]:
# url = 'https://listado.mercadolibre.com.ar/apple-watch#D[A:apple%20watch]'
url = 'https://www.basketball-reference.com/leagues/NBA_2020_per_game.html'

In [12]:
df = pd.read_html(url, header=0)
df

[      Rk                    Player Pos Age   Tm   G  GS    MP   FG   FGA  ...  \
 0      1              Steven Adams   C  26  OKC  63  63  26.7  4.5   7.6  ...
 1      2               Bam Adebayo  PF  22  MIA  72  72  33.6  6.1  11.0  ...
 2      3         LaMarcus Aldridge   C  34  SAS  53  53  33.1  7.4  15.0  ...
 3      4            Kyle Alexander   C  23  MIA   2   0   6.5  0.5   1.0  ...
 4      5  Nickeil Alexander-Walker  SG  21  NOP  47   1  12.6  2.1   5.7  ...
 ..   ...                       ...  ..  ..  ...  ..  ..   ...  ...   ...  ...
 672  525                Trae Young  PG  21  ATL  60  60  35.3  9.1  20.8  ...
 673  526               Cody Zeller   C  27  CHO  58  39  23.1  4.3   8.3  ...
 674  527              Tyler Zeller   C  30  SAS   2   0   2.0  0.5   2.0  ...
 675  528                Ante Žižić   C  23  CLE  22   0  10.0  1.9   3.3  ...
 676  529               Ivica Zubac   C  22  LAC  72  70  18.4  3.3   5.3  ...

       FT%  ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS
 0    .582  3.3  6.0   9.3  2.3  0.8  1.1  1.5  1.9  10.9
 1    .691  2.4  7.8  10.2  5.1  1.1  1.3  2.8  2.5  15.9
 2    .827  1.9  5.5   7.4  2.4  0.7  1.6  1.4  2.4  18.9
 3     NaN  1.0  0.5   1.5  0.0  0.0  0.0  0.5  0.5   1.0
 4    .676  0.2  1.6   1.8  1.9  0.4  0.2  1.1  1.2   5.7
 ..    ...  ...  ...   ...  ...  ...  ...  ...  ...   ...
 672  .860  0.5  3.7   4.3  9.3  1.1  0.1  4.8  1.7  29.6
 673  .682  2.8  4.3   7.1  1.5  0.7  0.4  1.3  2.4  11.1
 674   NaN  1.5  0.5   2.0  0.0  0.0  0.0  0.0  0.0   1.0
 675  .737  0.8  2.2   3.0  0.3  0.3  0.2  0.5  1.2   4.4
 676  .747  2.7  4.8   7.5  1.1  0.2  0.9  0.8  2.3   8.3

 [677 rows x 30 columns]]

In [14]:
df2020 = df[0]
df2020

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,...,.582,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,2,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,...,.691,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,3,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,4,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,...,NaN,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,5,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,...,.676,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,525,Trae Young,PG,21,ATL,60,60,35.3,9.1,20.8,...,.860,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6
673,526,Cody Zeller,C,27,CHO,58,39,23.1,4.3,8.3,...,.682,2.8,4.3,7.1,1.5,0.7,0.4,1.3,2.4,11.1
674,527,Tyler Zeller,C,30,SAS,2,0,2.0,0.5,2.0,...,NaN,1.5,0.5,2.0,0.0,0.0,0.0,0.0,0.0,1.0
675,528,Ante Žižić,C,23,CLE,22,0,10.0,1.9,3.3,...,.737,0.8,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4
676,529,Ivica Zubac,C,22,LAC,72,70,18.4,3.3,5.3,...,.747,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3

In [15]:
df2020.shape

(677, 30)

In [16]:
df2020['Year']= 2020

In [17]:
df2020.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,...,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9,2020
1,2,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,...,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9,2020
2,3,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,...,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9,2020
3,4,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,...,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0,2020
4,5,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,...,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7,2020

In [18]:
df2020.tail()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
672,525,Trae Young,PG,21,ATL,60,60,35.3,9.1,20.8,...,0.5,3.7,4.3,9.3,1.1,0.1,4.8,1.7,29.6,2020
673,526,Cody Zeller,C,27,CHO,58,39,23.1,4.3,8.3,...,2.8,4.3,7.1,1.5,0.7,0.4,1.3,2.4,11.1,2020
674,527,Tyler Zeller,C,30,SAS,2,0,2.0,0.5,2.0,...,1.5,0.5,2.0,0.0,0.0,0.0,0.0,0.0,1.0,2020
675,528,Ante Žižić,C,23,CLE,22,0,10.0,1.9,3.3,...,0.8,2.2,3.0,0.3,0.3,0.2,0.5,1.2,4.4,2020
676,529,Ivica Zubac,C,22,LAC,72,70,18.4,3.3,5.3,...,2.7,4.8,7.5,1.1,0.2,0.9,0.8,2.3,8.3,2020

In [22]:
df2020.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year'],
      dtype='object')

In [24]:
df2020.isnull().sum()

Rk         0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        2
3P         0
3PA        0
3P%       35
2P         0
2PA        0
2P%        6
eFG%       2
FT         0
FTA        0
FT%       33
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
dtype: int64